import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { MainWrapper } from "@/shared/components/MainWrapper/MainWrapper";

import "../styles/main.sass";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="es" className={raleway.variable}>
      <body>
        <MainWrapper>{children}</MainWrapper>
      </body>
    </html>
  );
}
